server:
  port: 8081
dubbo:
  application:
    name: cart-service
  registry:
    address: zookeeper://119.3.164.67:2181
  protocol:
    port: 20885
spring:
  redis:
    host: 119.3.164.67
    port: 6379
    password: java1909
    jedis:
      pool:
        max-active: 20
  datasource:
    url: jdbc:mysql://119.3.164.67:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
