
server:
  port: 8085
dubbo:
  application:
    name: search-service
  registry:
    address: zookeeper://119.3.164.67:2181
  protocol:
    port: 20884
spring:
  data:
    solr:
      host: http://119.3.164.67:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://119.3.164.67:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username:
    password:
    virtual-host:
imageServer: http://119.3.164.67:8888
