
server:
  port: 8083
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://119.3.164.67:2181
  protocol:
    port: 20883

spring:
  datasource:
    url: jdbc:mysql://119.3.164.67:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 119.3.164.67
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username:
    password:
    virtual-host:
activeAccountServer: http://119.3.164.67:8086/email/active?uuid=
