
server:
  port: 8088
dubbo:
  application:
    name: sso-consumer
  registry:
    address: zookeeper://119.3.164.67:2181
  consumer:
    timeout: 50000
spring:
  redis:
    host: 119.3.164.67
    port: 6379
    password: java1909
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: j1906