spring:
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: j1906
  redis:
    host: 119.3.164.67
    port: 6379
    password: java1909
    jedis:
      pool:
        max-active: 20
  mail:
    host: smtp.qq.com
    username: 1127042137@qq.com
    password: xnunqfzvddunijej
    default-encoding: utf-8
server:
  port: 8082


