
server:
  port: 8090
dubbo:
  application:
    name: product-consumer
  registry:
    address: zookeeper://119.3.164.67:2181
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 119.3.164.67:22122
imageServer: http://119.3.164.67:8888