
server:
  port: 8095
dubbo:
  application:
    name: mail-order
  registry:
    address: zookeeper://119.3.164.67:2181

spring:
  redis:
    host: 119.3.164.67
    port: 6379
    password: java1909
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: j1906