
server:
  port: 8084
dubbo:
  application:
    name: product-provider
  registry:
    address: zookeeper://119.3.164.67:2181
  protocol:
    port: 20881
spring:
  datasource:
    url: jdbc:mysql://119.3.164.67:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    host: 119.3.164.67
    port: 5672
    username:
    password:
    virtual-host: